#This is a Jekyll file to exclude directories to not be uploaded and be live in GitHub Pages of this Repository

exclude: 
  - "Additional-Material"
  - "Design-Material"
  - "Source-Code"
  - "This-Repository"